using System;
using System.IO;
using System.IO.Compression;
using FluentAssertions;
using Xunit;

namespace LiteDB.Tests.Database
{
    public class GuidCompatibility_Tests
    {
        private const string PreSpanSerializationDatabaseGzipBase64 =
            "H4sIAAAAAAAACu3cP0vDQBzG8eeSFgVBVHwBhwpCoQ666iK66VbBQSotTWug/qGtdtNV8Q3o7KbvQCd3Hd0UcXPSd2DkUqymLoqCqN8P5" +
            "Ai5ywVufX6/SJKJ3lI8OFaRMhmbWwnrNqzbgp0LG8HMtC2H1cBmMt1uoS/paH/pamrwttu905WSjKTJeAdJ977iHaMo2tH363NXZTMs1eP" +
            "PAgAAAAAAAAAAAADwL7nQ3Evm/+0c3eX/Lt9PTL8UB3x8/+WwpJExNxrPPXKDad0CAAAAAAAAAAAAAIDv4GJ4P9n67/J//9yT7jxPsh3hv" +
            "/euYAAflDhMzvFremVcbUqrOOW1rqRnYqhfCzPN8u7h8dnFzcOnilUAAAAAAAAAAAAA4JcZ1ak3b1bNvLFxf3+qHVC383+Tl7TtFscTi5L" +
            "SroPf/W4/1RmxprcK1c2gNXdwev2U2+obN8Ozlb2Ty0evWigGVQ1IatbCRiNYyxaD8notyG7UfvocAAAAAAAAAAAAAADQH5CX1TPbkOVcAI" +
            "AAAA==";

        private static readonly Guid ExpectedId =
            new Guid("00112233-4455-6677-8899-aabbccddeeff");

        private static readonly Guid ExpectedValue =
            new Guid("fedcba98-7654-3210-0123-456789abcdef");

        [Fact]
        public void Guid_values_written_before_span_serialization_are_read_unchanged()
        {
            // Generated by LiteDB at the PR merge base a50661a9, before the
            // span-based Guid reader and writer existed.
            using (var databaseStream = DecompressDatabase())
            using (var database = new LiteDatabase(databaseStream))
            {
                var document = database.GetCollection("guids").FindById(ExpectedId);

                Assert.NotNull(document);
                document["_id"].AsGuid.Should().Be(ExpectedId);
                document["value"].AsGuid.Should().Be(ExpectedValue);
                document["label"].AsString.Should().Be("written-before-pr");
            }
        }

        private static MemoryStream DecompressDatabase()
        {
            var compressedBytes = Convert.FromBase64String(PreSpanSerializationDatabaseGzipBase64);
            var compressedStream = new MemoryStream(compressedBytes);
            var databaseStream = new MemoryStream();

            using (compressedStream)
            using (var gzipStream = new GZipStream(compressedStream, CompressionMode.Decompress))
            {
                gzipStream.CopyTo(databaseStream);
            }

            databaseStream.Position = 0;

            return databaseStream;
        }
    }
}
